apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0 
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ${DOCKERHUB_USERNAME}/telemedicine-backend:${VERSION}
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secrets
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: mongo_uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: telemedicine-secrets
              key: jwt_secret
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 10