---
- name: Deploy Telemedicine App
  hosts: local
  become: false
  vars_files:
    - vault/secrets.yml
  
  tasks:
    - name: Create project directory if it doesn't exist
      file:
        path: "/tmp/telemedicine-app"
        state: directory
        mode: '0755'
      
    - name: Clean existing deployments
      file:
        path: "/tmp/telemedicine-app"
        state: absent
      
    - name: Create fresh project directory
      file:
        path: "/tmp/telemedicine-app"
        state: directory
        mode: '0755'
      
    - name: Copy project files from Jenkins workspace
      synchronize:
        src: "{{ playbook_dir }}/../"
        dest: "/tmp/telemedicine-app"
        rsync_opts:
          - "--exclude=.git"
      
    - name: Login to DockerHub
      command: docker login -u {{ docker_hub_username }} -p {{ docker_hub_password }}
      no_log: true
      
    - name: Create .env file
      copy:
        dest: "/tmp/telemedicine-app/Telemedicine-app/.env"
        content: |
          MONGO_URI={{ mongo_uri }}
          JWT_SECRET={{ jwt_secret }}
          NODE_ENV=production
          CLOUDINARY_CLOUD_NAME={{ cloudinary_cloud_name }}
          CLOUDINARY_API_KEY={{ cloudinary_api_key }}
          CLOUDINARY_API_SECRET={{ cloudinary_api_secret }}
          DEFAULT_ADMIN_EMAIL={{ default_admin_email }}
          DEFAULT_ADMIN_PASSWORD={{ default_admin_password }}

    - name: Build and start Docker containers
      command: docker compose up -d --build
      args:
        chdir: "/tmp/telemedicine-app/Telemedicine-app"
      environment:
        MONGO_URI: "{{ mongo_uri }}"
        JWT_SECRET: "{{ jwt_secret }}"
        
    - name: Wait for the application to start
      pause:
        seconds: 10
        
    - name: Verify containers are running
      command: docker ps
      register: docker_status
      
    - name: Show running containers
      debug:
        var: docker_status.stdout_lines